- pom.xml
using flow-component-base alpha3 and release repo;
using flow version 1.0.0.alpha9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/7)
> Prepare to Release

- README.md
- pom.xml
- src/test/java/com/vaadin/ui/tabs/TabsIT.java
- src/test/java/com/vaadin/ui/tabs/TabsView.java
this is related to ticket vaadin/flow#2795
+Update router titles;
+Override getTestPath();
+Update parent and dependency version to SNAPSHOT;
+Update README
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/9)
> Prepare to build Demo jar of the component

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/10)
> Add needed component dependencies

- src/test/java/com/vaadin/ui/tabs/demo/TabsView.java
- src/test/java/com/vaadin/ui/tabs/tests/TabTest.java
- src/test/java/com/vaadin/ui/tabs/tests/TabsIT.java
- src/test/java/com/vaadin/ui/tabs/tests/TabsTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/13)
> Refactor the repo structure

- src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTab.java
- src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTabs.java
- src/main/java/com/vaadin/flow/component/tabs/Tab.java
- src/main/java/com/vaadin/flow/component/tabs/Tabs.java
- src/test/java/com/vaadin/flow/component/tabs/demo/TabsView.java
- src/test/java/com/vaadin/flow/component/tabs/tests/TabTest.java
- src/test/java/com/vaadin/flow/component/tabs/tests/TabsIT.java
- src/test/java/com/vaadin/flow/component/tabs/tests/TabsTest.java
Part of package rename #3032
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/14)
> Rename package com.vaadin.ui to com.vaadin.flow.component

- src/test/java/com/vaadin/flow/component/tabs/demo/TabsView.java
- src/test/java/com/vaadin/flow/component/tabs/tests/TabsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/17)
> Change the demo to use Component::setVisible instead of CSS

- src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTab.java
- src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTabs.java
- src/test/java/com/vaadin/flow/component/tabs/demo/TabsView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/18)
> update component using the new webcomponent version

- src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTab.java
- src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTabs.java
- src/test/java/com/vaadin/flow/component/tabs/demo/TabsView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/21)
> Update the generated component and add lumo style to demos

- src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTab.java
- src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTabs.java
- src/main/java/com/vaadin/flow/component/tabs/Tab.java
- src/main/java/com/vaadin/flow/component/tabs/Tabs.java
- src/test/java/com/vaadin/flow/component/tabs/demo/TabsView.java
Fix for #2329
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/23)
> Revers accessors for "disabled" property.

- pom.xml
- src/test/java/com/vaadin/flow/component/tabs/demo/TabsView.java
enable logging;
remove HtmlImport from component demo;
rename repository ids
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/24)
> Using new webjars

- src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTabs.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/29)
> Regenerate tabs without the un-needed items sync

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/31)
> Fix Flow documentation link in ReadMe

- src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTab.java
- src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTabs.java
fix after vaadin/flow#3678
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/32)
> Update generated code

- pom.xml
- src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTab.java
- src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTabs.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/34)
> Update webcomponent to 2.0.0-beta3

- pom.xml
- src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTab.java
- src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTabs.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/35)
> Update webjars and generated code

- src/test/java/com/vaadin/flow/component/tabs/demo/TabsView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/37)
> Fix after renaming VaadinIcons to VaadinIcon

- pom.xml
- src/test/java/com/vaadin/flow/component/tabs/tests/TabsSerializableTest.java
Related to vaadin/platform#173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/38)
> Add serialization test

- pom.xml
- src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTab.java
- src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTabs.java
- src/main/java/com/vaadin/flow/component/tabs/TabVariant.java
- src/main/java/com/vaadin/flow/component/tabs/TabsVariant.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/45)
> Update webjar with Material Theme

- src/test/java/com/vaadin/flow/component/tabs/demo/TabsView.java
- src/test/java/com/vaadin/flow/component/tabs/tests/TabsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/49)
> Add demo about theme variant and tests

- src/main/java/com/vaadin/flow/component/tabs/Tabs.java
- src/test/java/com/vaadin/flow/component/tabs/tests/SelectedTabIT.java
- src/test/java/com/vaadin/flow/component/tabs/tests/SelectedTabPage.java
- src/test/java/com/vaadin/flow/component/tabs/tests/TabsTest.java
Fixes #51
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/53)
> Update isSelected state properly for tab inside Tabs component

- src/main/java/com/vaadin/flow/component/tabs/Tabs.java
- src/test/java/com/vaadin/flow/component/tabs/tests/SelectedTabIT.java
- src/test/java/com/vaadin/flow/component/tabs/tests/SelectedTabPage.java
- src/test/java/com/vaadin/flow/component/tabs/tests/TabsTest.java
Fixes #51 
Cherry-pick from master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/55)
> Update isSelected state properly for tab inside Tabs component (#53)

- src/main/java/com/vaadin/flow/component/tabs/Tab.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/56)
> Update javadocs to reflect the selected behavior if Tab in Tabs

- src/main/java/com/vaadin/flow/component/tabs/Tabs.java
- src/test/java/com/vaadin/flow/component/tabs/tests/SelectedTabIT.java
- src/test/java/com/vaadin/flow/component/tabs/tests/SelectedTabPage.java
Fixes #3932
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/58)
> Fire selection event if selected tab is changed but index is not

- src/main/java/com/vaadin/flow/component/tabs/Tabs.java
Fixes #61
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/62)
> Improve javadocs for addSelectedChangeListener.

- src/main/java/com/vaadin/flow/component/tabs/Tabs.java
Fixes #61
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/65)
> Improve javadocs for addSelectedChangeListener. (#62)

- src/main/java/com/vaadin/flow/component/tabs/Tabs.java
- src/test/java/com/vaadin/flow/component/tabs/tests/SelectedTabIT.java
- src/test/java/com/vaadin/flow/component/tabs/tests/SelectedTabPage.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/66)
> Prevent disabled tab selection (#63)

- src/main/java/com/vaadin/flow/component/tabs/Tabs.java
- src/test/java/com/vaadin/flow/component/tabs/tests/SelectedTabIT.java
- src/test/java/com/vaadin/flow/component/tabs/tests/SelectedTabPage.java
- src/test/java/com/vaadin/flow/component/tabs/tests/SelectionEventTest.java
!! Remember to use rebase-and-merge !!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/71)
> Cherrypick #58 and #68 from master

- src/main/java/com/vaadin/flow/component/tabs/Tabs.java
- src/test/java/com/vaadin/flow/component/tabs/tests/SelectedTabIT.java
- src/test/java/com/vaadin/flow/component/tabs/tests/SelectedTabPage.java
- src/test/java/com/vaadin/flow/component/tabs/tests/SelectionEventTest.java
- src/test/java/com/vaadin/flow/component/tabs/tests/TabsTest.java
either with setSelectedTab(null) or setSelectedIndex(-1)
Fixes #72
Fixes #70
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/73)
> Allow unselecting all tabs

- src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTab.java
- src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTabs.java
- src/main/java/com/vaadin/flow/component/tabs/TabVariant.java
- src/main/java/com/vaadin/flow/component/tabs/TabsVariant.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/80)
> Update java wrapper to stable version

- vaadin-tabs-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/85)
> Added necessary plugins

- README.md
- vaadin-tabs-flow-demo/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/86)
> Use compile scope for logger dependency and update readme

- pom.xml
- vaadin-tabs-flow-demo/pom.xml
- vaadin-tabs-flow-integration-tests/pom.xml
- vaadin-tabs-flow-testbench/pom.xml
- vaadin-tabs-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/89)
> Update to next minor and Use flow 1.5-SNAPSHOT

- vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/Tabs.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/93)
> Issue 91, fix it for add((Tab[])null), too.

- vaadin-tabs-flow-integration-tests/pom.xml
- vaadin-tabs-flow-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/96)
> Make TB artifactId consistent with other components

- pom.xml
- vaadin-tabs-flow-integration-tests/pom-bower-mode.xml
- vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTab.java
- vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTabs.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/97)
> Add bower mode tests

- vaadin-tabs-flow-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/98)
> Use flow-maven-plugin in integration test

- pom.xml
- vaadin-tabs-flow-testbench/pom.xml
- vaadin-tabs-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/101)
> Remove vaadin-component-testbench

- pom.xml
- vaadin-tabs-flow-demo/pom.xml
- vaadin-tabs-flow-integration-tests/pom.xml
- vaadin-tabs-flow-testbench/pom.xml
- vaadin-tabs-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/100)
> Remove vaadin components testbench

- pom.xml
- vaadin-tabs-flow-integration-tests/pom-bower-mode.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/106)
> Fix test build

- vaadin-tabs-flow/pom.xml
- vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTab.java
- vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTabs.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/107)
> Bump versions, update WC dependency to 3.0.2

- vaadin-tabs-flow/pom.xml
- vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTab.java
- vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTabs.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/109)
> Bump vaadin-tabs WC dependency to 3.0.4

- vaadin-tabs-flow-demo/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/113)
> Only use flow-maven-plugin when packaging is war

- vaadin-tabs-flow/pom.xml
- vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTab.java
- vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTabs.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/114)
> Bump vaadin-tabs WC dependency to 3.0.5

- vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/Tabs.java
Connected to https://github.com/vaadin/components-team-tasks/issues/483
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-tabs-flow/118)
> Update exception phrase

- vaadin-tabs-flow-demo/src/main/java/com/vaadin/flow/component/tabs/demo/TabsView.java
> Improve vaadin tab create tab with pages demo

- vaadin-tabs-flow-demo/src/main/java/com/vaadin/flow/component/tabs/demo/TabsView.java
This issue is for users to be able to use code correctly by copy-pasting
Depends on https://github.com/vaadin/flow/pull/8199/files
> Adding missing method to Vaadin Tab demos

- pom.xml
- vaadin-tabs-flow-demo/pom.xml
- vaadin-tabs-flow-integration-tests/pom-bower-mode.xml
- vaadin-tabs-flow-integration-tests/pom.xml
- vaadin-tabs-flow-testbench/pom.xml
- vaadin-tabs-flow/pom.xml
- vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTab.java
- vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTabs.java
* Bump snapshot version
* Bump flow-component-base (2.3-SNAPSHOT)
* Bump WC dependency
* Bump webjar dependencies
Part of vaadin/components-team-tasks#534
> Bump versions for V14.3

- vaadin-tabs-flow-demo/src/main/java/com/vaadin/flow/component/tabs/demo/TabsView.java
> Fix typo in TabsView

- vaadin-tabs-flow-demo/src/main/java/com/vaadin/flow/component/tabs/demo/TabsView.java
- vaadin-tabs-flow-integration-tests/src/test/java/com/vaadin/flow/component/tabs/tests/TabsIT.java
Remove unnecessary pages variable that created a div around the components and modify the code accordingly
> Improve create tabs with pages demo
